server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates your tables based on your Java entities
    show-sql: true # Prints the SQL queries in your console (great for debugging)
